### ISSUE TITLE
Bug? Remote Port is always 9001

### ISSUE THREAD

**Issue by huddx01** [brookstalley/homebridge-osc#2]
@brookstalley 
Hi, first of all - very inspirating and cool project! 
I am trying to control some of my audio-gear controls  (buttons, sliders, etc) via HB and your osc plugin.

1) Maybe a bug in line 93?
https://github.com/brookstalley/homebridge-osc/blob/9c6b0127a542b9f7faffa54d21a23103bad14d6a/index.js#L93C2-L93C56
I think, it should be: 
`this.remotePort = parseInt(config["remotePort"] || 9001);
`

2) Maybe you have an idea how it would be best prachtice to add more than one service to the same accessory?
OK - i could add multiple accessories. But each of them uses its own ports...
Scenario: 
The remote host has different buttons, sliders, etc, which have its own OSC paths. But it is reachable under one singel IP and UDP port:
- channel1 solo: /1/solo/1
- channel2 solo: /1solo/2
- channel1 mute: /1/mute/1
- channel2 mute: /1/mute/2
and so on...

Thanks in advance!

**Comment by brookstalley** [comment]
Thanks for the note! Yes, like 93 looks wrong.

I'm actually just getting back to this after a few years away and will have to re-learn OSC and this software. I think you're right that a single host:port can support multiple paths for different commands. It may be a couple of weeks, but I do need to get this going, so I'll report back once I get it configured again :)
